### PR TITLE
Add support for amd, commonjs and browser module

### PR DESCRIPTION
**Pull request by francbartoli**

### CODE REVIEW

**Comment by walkermatt** [comment]
Hi, I think these changes require users of the lib to use CommonJS and hence a build step. I'm happy to add support for CommonJS but I don't want that to be the only option. Perhaps we need to look at a something like https://github.com/umdjs/umd?

**Comment by francbartoli** [comment]
Hi, yes it will be definitively more complete. Trying to come back with something useful.

**Comment by francbartoli** [comment]
It should now include others options

**Comment by walkermatt** [comment]
@francbartoli I'll try and pull together some example projects for CommonJS and AMD. This looks like a good starting point for [CommonJS/ Browserify](https://openlayers.org/en/latest/doc/tutorials/browserify.html), any ideas for AMD?

**Comment by francbartoli** [comment]
@walkermatt the last commit should now include AMD as well. I'm using it with browserify [here](http://geoavalanche.org/mygeoss/public/) and is working well. I don't have examples with AMD though.

**Pull request merged**
