### PR TITLE
Prepare ol3-layerswitcher to registry in Bower

### PR DESCRIPTION
**Pull request by michogar**
Hi, 

we need install the layerswitcher from Bower and we have prepared your library to registry it in this package manager. In our repo we have prepared the library to registry (tagged correctly), but we think is better registry the library from your repo. If you accept this pull-request you must tagged the version correctly [Semantic Versioning](http://bower.io/docs/creating-packages/#register) and we can register it after in Bower.

Thanks, and keep in touch.

Regards.

### CODE REVIEW

**Comment by walkermatt** [comment]
@michogar thanks, very happy in principle :+1: 

I'll review fully over the next few days. An initial thought is that the examples should probably revert to using the hosted OpenLayers build to avoid having to commit node_modules.

Out of interest how are you handling the dependency on OpenLayers in your app? Are you installing using Bower from GitHub?

**Comment by walkermatt** [comment]
I've had a look at this over the weekend and I'm aiming to merge, tag and register with Bower tomorrow.

**Comment by walkermatt** [comment]
I've gone for `v1.0.0` as the initial released version; now registered with Bower.

@michogar thanks for your work on this, I think I'll also do the same for [walkermatt/ol3-popup](https://github.com/walkermatt/ol3-popup).

**Comment by michogar** [comment]
Hi Matt,

thanks to you, great work!. 

In our examples we are using Openlayers from a CDN. We are working in a stack of samples to show the power of an API, and consume OL3 from a CDN is ok.

Thanks again for your work.

**Pull request closed without merging**
